# Generated by Django 3.0.6 on 2022-01-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_scrape', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='H1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='h1', max_length=1000)),
                ('inner_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('class_name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='H2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='h2', max_length=1000)),
                ('inner_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('class_name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='img', max_length=1000)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='paragraph', max_length=1000)),
                ('inner_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('class_name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='tag',
            field=models.CharField(default='A', max_length=1000),
        ),
    ]
